### ISSUE TITLE
Work with Emmet

### ISSUE THREAD

**Issue by CreateSean** [addisonhall/language-expressionengine-templates#1]
I'm trying to get this to work with Emmet following the instructions here: **https://github.com/emmetio/emmet-atom#tab-key**

However I am unable to figure out what grammar expressionengine is using to get it to work with Emmet. Please advise.

**Comment by addisonhall** [comment]
Here's what I added to my keymap.cson file:

```
'atom-text-editor[data-grammar="text html ee"]:not([mini])':
    'tab': 'emmet:expand-abbreviation-with-tab'
```

I'm not sure if you can add Emmet support directly to a grammar... That would be nice.
