### ISSUE TITLE
Syntax highlighting doesn't work with "const"

### ISSUE THREAD

**Issue by samnau** [addisonhall/language-expressionengine-templates#2]
This works great with `let` and `var` but for some reason `const` breaks syntax highlighting.

**Comment by addisonhall** [comment]
Hey, samnau. Can you give me an example?

**Comment by samnau** [comment]
Well when I use a template string like this:
```
const htmlTemplate = `
<div>
Content
</div>
`
```
The HTML syntax highlighting stops working and it's just a normal string again. If I use it as a `var` or a `let` it still works. 

Now to be specific, I was using the the Atom grammar setting for `Javascript (Rails)`. I found a workaround by setting the grammar to `Regular Expressions (Javascript)` which allows your package to start working again. Unfortunately, I lose most of my JS highlighting that isn't part of the template string.

**Comment by addisonhall** [comment]
I think perhaps there's a misunderstanding as to what this package does... This package provides syntax highlighting for the custom templating language in the [ExpressionEngine content management system](https://expressionengine.com/).

**Comment by samnau** [comment]
Ok. This is embarrassing. I think I opened a bug for this and one other library and got confused. Sorry!

**Comment by addisonhall** [comment]
No worries!
